/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        'surface-dim': "var(--color-surface-dim)",
        'surface-bright': "var(--color-surface-bright)",
        'surface-container-lowest': "var(--color-surface-container-lowest)",
        'surface-container-low': "var(--color-surface-container-low)",
        'surface-container': "var(--color-surface-container)",
        'surface-container-high': "var(--color-surface-container-high)",
        'surface-container-highest': "var(--color-surface-container-highest)",
        'on-surface': "var(--color-on-surface)",
        'on-surface-variant': "var(--color-on-surface-variant)",
        'inverse-surface': "var(--color-inverse-surface)",
        'inverse-on-surface': "var(--color-inverse-on-surface)",
        outline: "var(--color-outline)",
        'outline-variant': "var(--color-outline-variant)",
        'surface-tint': "var(--color-surface-tint)",
        primary: "var(--color-primary)",
        'on-primary': "var(--color-on-primary)",
        'primary-container': "var(--color-primary-container)",
        'on-primary-container': "var(--color-on-primary-container)",
        'inverse-primary': "var(--color-inverse-primary)",
        secondary: "var(--color-secondary)",
        'on-secondary': "var(--color-on-secondary)",
        'secondary-container': "var(--color-secondary-container)",
        'on-secondary-container': "var(--color-on-secondary-container)",
        tertiary: "var(--color-tertiary)",
        'on-tertiary': "var(--color-on-tertiary)",
        'tertiary-container': "var(--color-tertiary-container)",
        'on-tertiary-container': "var(--color-on-tertiary-container)",
        error: "var(--color-error)",
        'on-error': "var(--color-on-error)",
        'error-container': "var(--color-error-container)",
        'on-error-container': "var(--color-on-error-container)",
        'primary-fixed': "var(--color-primary-fixed)",
        'primary-fixed-dim': "var(--color-primary-fixed-dim)",
        'on-primary-fixed': "var(--color-on-primary-fixed)",
        'on-primary-fixed-variant': "var(--color-on-primary-fixed-variant)",
        'secondary-fixed': "var(--color-secondary-fixed)",
        'secondary-fixed-dim': "var(--color-secondary-fixed-dim)",
        'on-secondary-fixed': "var(--color-on-secondary-fixed)",
        'on-secondary-fixed-variant': "var(--color-on-secondary-fixed-variant)",
        'tertiary-fixed': "var(--color-tertiary-fixed)",
        'tertiary-fixed-dim': "var(--color-tertiary-fixed-dim)",
        'on-tertiary-fixed': "var(--color-on-tertiary-fixed)",
        'on-tertiary-fixed-variant': "var(--color-on-tertiary-fixed-variant)",
        background: "var(--color-background)",
        'on-background': "var(--color-on-background)",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-currency': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'touch-target-min': '48px',
        'container-margin': '16px',
        gutter: '12px',
      },
      boxShadow: {
        'level-1': '0px 4px 12px rgba(0, 0, 0, 0.05)',
        'level-2': '0px 8px 24px rgba(0, 0, 0, 0.1)',
      }
    },
  },
  plugins: [],
}