export const MOCK_POOLS = [
  {
    id: "1",
    title: "December Holiday Fund",
    totalAmount: 50000,
    contributionPerWeek: 5000,
    totalMembers: 10,
    status: "Active",
    isPublic: false,
    isJoined: true,
  },
  {
    id: "2",
    title: "New Year Vacation",
    totalAmount: 20000,
    contributionPerWeek: 4000,
    totalMembers: 5,
    status: "Pending",
    isPublic: false,
    isJoined: true,
  },
  {
    id: "3",
    title: "Gadget Savings",
    totalAmount: 120000,
    contributionPerWeek: 10000,
    totalMembers: 12,
    status: "Active",
    isPublic: false,
    isJoined: true,
  },
  {
    id: "4",
    title: "Community Fund 2026",
    totalAmount: 500000,
    contributionPerWeek: 1000,
    totalMembers: 150,
    status: "Active",
    isPublic: true,
    isJoined: true,
  },
  {
    id: "5",
    title: "Small Business Starter",
    totalAmount: 250000,
    contributionPerWeek: 2500,
    totalMembers: 50,
    status: "Pending",
    isPublic: true,
    isJoined: false,
  },
];
